pretrained_base_model_path: './pretrained_model/stable-diffusion-v1-5'
pretrained_vae_path: './pretrained_model/sd-vae-ft-mse'
image_encoder_path: './pretrained_model/image_encoder'

denoising_unet_path: "./pretrained_model/denoising_unet.pth"
reference_unet_path: "./pretrained_model/reference_unet.pth"
pose_guider_path: "./pretrained_model/pose_guider.pth"
motion_module_path: "./pretrained_model/motion_module.pth"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  # "./configs/inference/ref_images/guile.png":
  #   - "./configs/inference/pose_images/guile"
  # "./configs/inference/ref_images/Alice.png":
  #   - "./configs/inference/pose_images/Alice"
  # "./configs/inference/ref_images/kawa.png":
  #   - "./configs/inference/pose_images/kawa"
  # "./configs/inference/ref_images/Freeknight.png":
  #   - "./configs/inference/pose_images/Freeknight"
  # "./configs/inference/ref_images/William.png":
  #   - "./configs/inference/pose_images/William"
  # "./configs/inference/ref_images/cute_girl.png":
  #   - "./configs/inference/pose_images/cute_girl_jump"
  # "./configs/inference/ref_images/adventure_girl.png":
  #   - "./configs/inference/pose_images/adventure_girl_dead"
  "./configs/inference/ref_images/dog.png":
    - "./configs/inference/pose_images/dog_fall"
